#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_POKE_BALL 1
#define ITEM_GREAT_BALL 2
#define ITEM_ULTRA_BALL 3
#define ITEM_MASTER_BALL 4
#define ITEM_PREMIER_BALL 5
#define ITEM_HEAL_BALL 6
#define ITEM_NET_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_DIVE_BALL 9
#define ITEM_DUSK_BALL 10
#define ITEM_TIMER_BALL 11
#define ITEM_QUICK_BALL 12
#define ITEM_REPEAT_BALL 13
#define ITEM_LUXURY_BALL 14
#define ITEM_LEVEL_BALL 15
#define ITEM_LURE_BALL 16
#define ITEM_MOON_BALL 17
#define ITEM_FRIEND_BALL 18
#define ITEM_LOVE_BALL 19
#define ITEM_FAST_BALL 20
#define ITEM_HEAVY_BALL 21
#define ITEM_DREAM_BALL 22
#define ITEM_SAFARI_BALL 23
#define ITEM_SPORT_BALL 24
#define ITEM_PARK_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_CHERISH_BALL 27

// Note: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
// Several places expect the ball IDs to be first and contiguous (e.g. MON_DATA_POKEBALL)
// If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_034 for example)
#define FIRST_BALL ITEM_POKE_BALL
#define LAST_BALL ITEM_CHERISH_BALL

// Medicine
#define ITEM_POTION 28
#define ITEM_SUPER_POTION 29
#define ITEM_HYPER_POTION 30
#define ITEM_MAX_POTION 31
#define ITEM_FULL_RESTORE 32
#define ITEM_REVIVE 33
#define ITEM_MAX_REVIVE 34
#define ITEM_FRESH_WATER 35
#define ITEM_SODA_POP 36
#define ITEM_LEMONADE 37
#define ITEM_MOOMOO_MILK 38
#define ITEM_ENERGY_POWDER 39
#define ITEM_ENERGYPOWDER ITEM_ENERGY_POWDER // Pre-Gen VI name
#define ITEM_ENERGY_ROOT 40
#define ITEM_HEAL_POWDER 41
#define ITEM_REVIVAL_HERB 42
#define ITEM_ANTIDOTE 43
#define ITEM_PARALYZE_HEAL 44
#define ITEM_PARLYZ_HEAL ITEM_PARALYZE_HEAL // Pre-Gen VI name
#define ITEM_BURN_HEAL 45
#define ITEM_ICE_HEAL 46
#define ITEM_AWAKENING 47
#define ITEM_FULL_HEAL 48
#define ITEM_ETHER 49
#define ITEM_MAX_ETHER 50
#define ITEM_ELIXIR 51
#define ITEM_ELIXER ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR 52
#define ITEM_MAX_ELIXER ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE 53
#define ITEM_SACRED_ASH 54
#define ITEM_SWEET_HEART 55
#define ITEM_MAX_HONEY 56

// Regional Specialties
#define ITEM_PEWTER_CRUNCHIES 57
#define ITEM_RAGE_CANDY_BAR 58
#define ITEM_RAGECANDYBAR ITEM_RAGE_CANDY_BAR // Pre-Gen VI name
#define ITEM_LAVA_COOKIE 59
#define ITEM_OLD_GATEAU 60
#define ITEM_CASTELIACONE 61
#define ITEM_LUMIOSE_GALETTE 62
#define ITEM_SHALOUR_SABLE 63
#define ITEM_BIG_MALASADA 64

// Vitamins
#define ITEM_HP_UP 65
#define ITEM_PROTEIN 66
#define ITEM_IRON 67
#define ITEM_CALCIUM 68
#define ITEM_ZINC 69
#define ITEM_CARBOS 70
#define ITEM_PP_UP 71
#define ITEM_PP_MAX 72

// EV Feathers
#define ITEM_HEALTH_FEATHER 73
#define ITEM_HEALTH_WING ITEM_HEALTH_FEATHER // Pre-Gen VIII name
#define ITEM_MUSCLE_FEATHER 74
#define ITEM_MUSCLE_WING ITEM_MUSCLE_FEATHER // Pre-Gen VIII name
#define ITEM_RESIST_FEATHER 75
#define ITEM_RESIST_WING ITEM_RESIST_FEATHER // Pre-Gen VIII name
#define ITEM_GENIUS_FEATHER 76
#define ITEM_GENIUS_WING ITEM_GENIUS_FEATHER // Pre-Gen VIII name
#define ITEM_CLEVER_FEATHER 77
#define ITEM_CLEVER_WING ITEM_CLEVER_FEATHER // Pre-Gen VIII name
#define ITEM_SWIFT_FEATHER 78
#define ITEM_SWIFT_WING ITEM_SWIFT_FEATHER // Pre-Gen VIII name

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 79
#define ITEM_ABILITY_PATCH 80


// Candy
#define ITEM_RARE_CANDY 81
#define ITEM_EXP_CANDY_XS 82
#define ITEM_EXP_CANDY_S 83
#define ITEM_EXP_CANDY_M 84
#define ITEM_EXP_CANDY_L 85
#define ITEM_EXP_CANDY_XL 86
#define ITEM_DYNAMAX_CANDY 87

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 88
#define ITEM_YELLOW_FLUTE 89
#define ITEM_RED_FLUTE 90

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 91
#define ITEM_WHITE_FLUTE 92

// Encounter Modifiers
#define ITEM_REPEL 93
#define ITEM_SUPER_REPEL 94
#define ITEM_MAX_REPEL 95
#define ITEM_LURE 96
#define ITEM_SUPER_LURE 97
#define ITEM_MAX_LURE 98

#define ITEM_ESCAPE_ROPE 99

// X Items
#define ITEM_X_ATTACK 100
#define ITEM_X_DEFENSE 101
#define ITEM_X_DEFEND ITEM_X_DEFENSE // Pre-Gen VI name
#define ITEM_X_SP_ATK 102
#define ITEM_X_SPECIAL ITEM_X_SP_ATK // Pre-Gen VI name
#define ITEM_X_SP_DEF 103
#define ITEM_X_SPEED 104
#define ITEM_X_ACCURACY 105

#define ITEM_DIRE_HIT 106
#define ITEM_GUARD_SPEC 107

// Escape Items
#define ITEM_POKE_DOLL 108
#define ITEM_FLUFFY_TAIL 109
#define ITEM_POKE_TOY 110

#define ITEM_MAX_MUSHROOMS 111

// Treasures
#define ITEM_BOTTLE_CAP 112
#define ITEM_GOLD_BOTTLE_CAP 113
#define ITEM_NUGGET 114
#define ITEM_BIG_NUGGET 115
#define ITEM_TINY_MUSHROOM 116
#define ITEM_TINYMUSHROOM ITEM_TINY_MUSHROOM // Pre-Gen VI name
#define ITEM_BIG_MUSHROOM 117
#define ITEM_BALM_MUSHROOM 118
#define ITEM_BALMMUSHROOM ITEM_BALM_MUSHROOM // Pre-Gen VI name
#define ITEM_PEARL 119
#define ITEM_BIG_PEARL 120
#define ITEM_PEARL_STRING 121
#define ITEM_STARDUST 122
#define ITEM_STAR_PIECE 123
#define ITEM_COMET_SHARD 124
#define ITEM_SHOAL_SALT 125
#define ITEM_SHOAL_SHELL 126
#define ITEM_RED_SHARD 127
#define ITEM_BLUE_SHARD 128
#define ITEM_YELLOW_SHARD 129
#define ITEM_GREEN_SHARD 130
#define ITEM_HEART_SCALE 131
#define ITEM_HONEY 132
#define ITEM_RARE_BONE 133
#define ITEM_ODD_KEYSTONE 134
#define ITEM_PRETTY_FEATHER 135
#define ITEM_PRETTY_WING ITEM_PRETTY_FEATHER // Pre-Gen VIII name
#define ITEM_RELIC_COPPER 136
#define ITEM_RELIC_SILVER 137
#define ITEM_RELIC_GOLD 138
#define ITEM_RELIC_VASE 139
#define ITEM_RELIC_BAND 140
#define ITEM_RELIC_STATUE 141
#define ITEM_RELIC_CROWN 142
#define ITEM_STRANGE_SOUVENIR 143

// Fossils
#define ITEM_HELIX_FOSSIL 144
#define ITEM_DOME_FOSSIL 145
#define ITEM_OLD_AMBER 146
#define ITEM_ROOT_FOSSIL 147
#define ITEM_CLAW_FOSSIL 148
#define ITEM_ARMOR_FOSSIL 149
#define ITEM_SKULL_FOSSIL 150
#define ITEM_COVER_FOSSIL 151
#define ITEM_PLUME_FOSSIL 152
#define ITEM_JAW_FOSSIL 153
#define ITEM_SAIL_FOSSIL 154
#define ITEM_FOSSILIZED_BIRD 155
#define ITEM_FOSSILIZED_FISH 156
#define ITEM_FOSSILIZED_DRAKE 157
#define ITEM_FOSSILIZED_DINO 158

// Mulch
#define ITEM_GROWTH_MULCH 159
#define ITEM_DAMP_MULCH 160
#define ITEM_STABLE_MULCH 161
#define ITEM_GOOEY_MULCH 162
#define ITEM_RICH_MULCH 163
#define ITEM_SURPRISE_MULCH 164
#define ITEM_BOOST_MULCH 165
#define ITEM_AMAZE_MULCH 166

#define ITEM_WISHING_PIECE 167
#define ITEM_GALARICA_TWIG 168
#define ITEM_ARMORITE_ORE 169
#define ITEM_DYNITE_ORE 170

// Mail
#define ITEM_ORANGE_MAIL 171
#define ITEM_HARBOR_MAIL 172
#define ITEM_GLITTER_MAIL 173
#define ITEM_MECH_MAIL 174
#define ITEM_WOOD_MAIL 175
#define ITEM_WAVE_MAIL 176
#define ITEM_BEAD_MAIL 177
#define ITEM_SHADOW_MAIL 178
#define ITEM_TROPIC_MAIL 179
#define ITEM_DREAM_MAIL 180
#define ITEM_FAB_MAIL 181
#define ITEM_RETRO_MAIL 182

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define ITEM_FIRE_STONE 183
#define ITEM_WATER_STONE 184
#define ITEM_THUNDER_STONE 185
#define ITEM_THUNDERSTONE ITEM_THUNDER_STONE // Pre-Gen VI name
#define ITEM_LEAF_STONE 186
#define ITEM_ICE_STONE 187
#define ITEM_SUN_STONE 188
#define ITEM_MOON_STONE 189
#define ITEM_SHINY_STONE 190
#define ITEM_DUSK_STONE 191
#define ITEM_DAWN_STONE 192
#define ITEM_SWEET_APPLE 193
#define ITEM_TART_APPLE 194
#define ITEM_CRACKED_POT 195
#define ITEM_CHIPPED_POT 196
#define ITEM_GALARICA_CUFF 197
#define ITEM_GALARICA_WREATH 198
#define ITEM_DRAGON_SCALE 199
#define ITEM_UPGRADE 200
#define ITEM_UP_GRADE ITEM_UPGRADE // Pre-Gen VIII name
#define ITEM_PROTECTOR 201
#define ITEM_ELECTIRIZER 202
#define ITEM_MAGMARIZER 203
#define ITEM_DUBIOUS_DISC 204
#define ITEM_REAPER_CLOTH 205
#define ITEM_PRISM_SCALE 206
#define ITEM_WHIPPED_DREAM 207
#define ITEM_SACHET 208
#define ITEM_OVAL_STONE 209
#define ITEM_STRAWBERRY_SWEET 210
#define ITEM_LOVE_SWEET 211
#define ITEM_BERRY_SWEET 212
#define ITEM_CLOVER_SWEET 213
#define ITEM_FLOWER_SWEET 214
#define ITEM_STAR_SWEET 215
#define ITEM_RIBBON_SWEET 216

#define ITEM_EVERSTONE 217

// Nectars
#define ITEM_RED_NECTAR 218
#define ITEM_YELLOW_NECTAR 219
#define ITEM_PINK_NECTAR 220
#define ITEM_PURPLE_NECTAR 221

// Plates
#define ITEM_FLAME_PLATE 222
#define ITEM_SPLASH_PLATE 223
#define ITEM_ZAP_PLATE 224
#define ITEM_MEADOW_PLATE 225
#define ITEM_ICICLE_PLATE 226
#define ITEM_FIST_PLATE 227
#define ITEM_TOXIC_PLATE 228
#define ITEM_EARTH_PLATE 229
#define ITEM_SKY_PLATE 230
#define ITEM_MIND_PLATE 231
#define ITEM_INSECT_PLATE 232
#define ITEM_STONE_PLATE 233
#define ITEM_SPOOKY_PLATE 234
#define ITEM_DRACO_PLATE 235
#define ITEM_DREAD_PLATE 236
#define ITEM_IRON_PLATE 237
#define ITEM_PIXIE_PLATE 238

// Drives
#define ITEM_DOUSE_DRIVE 239
#define ITEM_SHOCK_DRIVE 240
#define ITEM_BURN_DRIVE 241
#define ITEM_CHILL_DRIVE 242

// Memories
#define ITEM_FIRE_MEMORY 243
#define ITEM_WATER_MEMORY 244
#define ITEM_ELECTRIC_MEMORY 245
#define ITEM_GRASS_MEMORY 246
#define ITEM_ICE_MEMORY 247
#define ITEM_FIGHTING_MEMORY 248
#define ITEM_POISON_MEMORY 249
#define ITEM_GROUND_MEMORY 250
#define ITEM_FLYING_MEMORY 251
#define ITEM_PSYCHIC_MEMORY 252
#define ITEM_BUG_MEMORY 253
#define ITEM_ROCK_MEMORY 254
#define ITEM_GHOST_MEMORY 255
#define ITEM_DRAGON_MEMORY 256
#define ITEM_DARK_MEMORY 257
#define ITEM_STEEL_MEMORY 258
#define ITEM_FAIRY_MEMORY 259

#define ITEM_RUSTED_SWORD 260
#define ITEM_RUSTED_SHIELD 261

// Colored Orbs
#define ITEM_RED_ORB 262
#define ITEM_BLUE_ORB 263

// Mega Stones
#define ITEM_VENUSAURITE 264
#define ITEM_CHARIZARDITE_X 265
#define ITEM_CHARIZARDITE_Y 266
#define ITEM_BLASTOISINITE 267
#define ITEM_BEEDRILLITE 268
#define ITEM_PIDGEOTITE 269
#define ITEM_ALAKAZITE 270
#define ITEM_SLOWBRONITE 271
#define ITEM_GENGARITE 272
#define ITEM_KANGASKHANITE 273
#define ITEM_PINSIRITE 274
#define ITEM_GYARADOSITE 275
#define ITEM_AERODACTYLITE 276
#define ITEM_MEWTWONITE_X 277
#define ITEM_MEWTWONITE_Y 278
#define ITEM_AMPHAROSITE 279
#define ITEM_STEELIXITE 280
#define ITEM_SCIZORITE 281
#define ITEM_HERACRONITE 282
#define ITEM_HOUNDOOMINITE 283
#define ITEM_TYRANITARITE 284
#define ITEM_SCEPTILITE 285
#define ITEM_BLAZIKENITE 286
#define ITEM_SWAMPERTITE 287
#define ITEM_GARDEVOIRITE 288
#define ITEM_SABLENITE 289
#define ITEM_MAWILITE 290
#define ITEM_AGGRONITE 291
#define ITEM_MEDICHAMITE 292
#define ITEM_MANECTITE 293
#define ITEM_SHARPEDONITE 294
#define ITEM_CAMERUPTITE 295
#define ITEM_ALTARIANITE 296
#define ITEM_BANETTITE 297
#define ITEM_ABSOLITE 298
#define ITEM_GLALITITE 299
#define ITEM_SALAMENCITE 300
#define ITEM_METAGROSSITE 301
#define ITEM_LATIASITE 302
#define ITEM_LATIOSITE 303
#define ITEM_LOPUNNITE 304
#define ITEM_GARCHOMPITE 305
#define ITEM_LUCARIONITE 306
#define ITEM_ABOMASITE 307
#define ITEM_GALLADITE 308
#define ITEM_AUDINITE 309
#define ITEM_DIANCITE 310

// Gems
#define ITEM_NORMAL_GEM 311
#define ITEM_FIRE_GEM 312
#define ITEM_WATER_GEM 313
#define ITEM_ELECTRIC_GEM 314
#define ITEM_GRASS_GEM 315
#define ITEM_ICE_GEM 316
#define ITEM_FIGHTING_GEM 317
#define ITEM_POISON_GEM 318
#define ITEM_GROUND_GEM 319
#define ITEM_FLYING_GEM 320
#define ITEM_PSYCHIC_GEM 321
#define ITEM_BUG_GEM 322
#define ITEM_ROCK_GEM 323
#define ITEM_GHOST_GEM 324
#define ITEM_DRAGON_GEM 325
#define ITEM_DARK_GEM 326
#define ITEM_STEEL_GEM 327
#define ITEM_FAIRY_GEM 328

// Z-Crystals
#define ITEM_NORMALIUM_Z 329
#define ITEM_FIRIUM_Z 330
#define ITEM_WATERIUM_Z 331
#define ITEM_ELECTRIUM_Z 332
#define ITEM_GRASSIUM_Z 333
#define ITEM_ICIUM_Z 334
#define ITEM_FIGHTINIUM_Z 335
#define ITEM_POISONIUM_Z 336
#define ITEM_GROUNDIUM_Z 337
#define ITEM_FLYINIUM_Z 338
#define ITEM_PSYCHIUM_Z 339
#define ITEM_BUGINIUM_Z 340
#define ITEM_ROCKIUM_Z 341
#define ITEM_GHOSTIUM_Z 342
#define ITEM_DRAGONIUM_Z 343
#define ITEM_DARKINIUM_Z 344
#define ITEM_STEELIUM_Z 345
#define ITEM_FAIRIUM_Z 346
#define ITEM_PIKANIUM_Z 347
#define ITEM_EEVIUM_Z 348
#define ITEM_SNORLIUM_Z 349
#define ITEM_MEWNIUM_Z 350
#define ITEM_DECIDIUM_Z 351
#define ITEM_INCINIUM_Z 352
#define ITEM_PRIMARIUM_Z 353
#define ITEM_LYCANIUM_Z 354
#define ITEM_MIMIKIUM_Z 355
#define ITEM_KOMMONIUM_Z 356
#define ITEM_TAPUNIUM_Z 357
#define ITEM_SOLGANIUM_Z 358
#define ITEM_LUNALIUM_Z 359
#define ITEM_MARSHADIUM_Z 360
#define ITEM_ALORAICHIUM_Z 361
#define ITEM_PIKASHUNIUM_Z 362
#define ITEM_ULTRANECROZIUM_Z 363

// Species-specific Held Items
#define ITEM_LIGHT_BALL 364
#define ITEM_LEEK 365
#define ITEM_STICK ITEM_LEEK // Pre-Gen VIII name
#define ITEM_THICK_CLUB 366
#define ITEM_LUCKY_PUNCH 367
#define ITEM_METAL_POWDER 368
#define ITEM_QUICK_POWDER 369
#define ITEM_DEEP_SEA_SCALE 370
#define ITEM_DEEPSEASCALE ITEM_DEEP_SEA_SCALE // Pre-Gen VI name
#define ITEM_DEEP_SEA_TOOTH 371
#define ITEM_DEEPSEATOOTH ITEM_DEEP_SEA_TOOTH // Pre-Gen VI name
#define ITEM_SOUL_DEW 372
#define ITEM_ADAMANT_ORB 373
#define ITEM_LUSTROUS_ORB 374
#define ITEM_GRISEOUS_ORB 375

// Incenses
#define ITEM_SEA_INCENSE 376
#define ITEM_LAX_INCENSE 377
#define ITEM_ODD_INCENSE 378
#define ITEM_ROCK_INCENSE 379
#define ITEM_FULL_INCENSE 380
#define ITEM_WAVE_INCENSE 381
#define ITEM_ROSE_INCENSE 382
#define ITEM_LUCK_INCENSE 383
#define ITEM_PURE_INCENSE 384

// Contest Scarves
#define ITEM_RED_SCARF 385
#define ITEM_BLUE_SCARF 386
#define ITEM_PINK_SCARF 387
#define ITEM_GREEN_SCARF 388
#define ITEM_YELLOW_SCARF 389

// EV Gain Modifiers
#define ITEM_MACHO_BRACE 390
#define ITEM_POWER_WEIGHT 391
#define ITEM_POWER_BRACER 392
#define ITEM_POWER_BELT 393
#define ITEM_POWER_LENS 394
#define ITEM_POWER_BAND 395
#define ITEM_POWER_ANKLET 396

// Type-boosting Held Items
#define ITEM_SILK_SCARF 397
#define ITEM_CHARCOAL 398
#define ITEM_MYSTIC_WATER 399
#define ITEM_MAGNET 400
#define ITEM_MIRACLE_SEED 401
#define ITEM_NEVER_MELT_ICE 402
#define ITEM_NEVERMELTICE ITEM_NEVER_MELT_ICE // Pre-Gen VI name
#define ITEM_BLACK_BELT 403
#define ITEM_BLACKBELT ITEM_BLACK_BELT // Gen II name
#define ITEM_POISON_BARB 404
#define ITEM_SOFT_SAND 405
#define ITEM_SHARP_BEAK 406
#define ITEM_TWISTED_SPOON 407
#define ITEM_TWISTEDSPOON ITEM_TWISTED_SPOON // Pre-Gen VI name
#define ITEM_SILVER_POWDER 408
#define ITEM_SILVERPOWDER ITEM_SILVER_POWDER // Pre-Gen VI name
#define ITEM_HARD_STONE 409
#define ITEM_SPELL_TAG 410
#define ITEM_DRAGON_FANG 411
#define ITEM_BLACK_GLASSES 412
#define ITEM_BLACKGLASSES ITEM_BLACK_GLASSES // Pre-Gen VI name
#define ITEM_METAL_COAT 413

// Choice Items
#define ITEM_CHOICE_BAND 414
#define ITEM_CHOICE_SPECS 415
#define ITEM_CHOICE_SCARF 416

// Status Orbs
#define ITEM_FLAME_ORB 417
#define ITEM_TOXIC_ORB 418

// Weather Rocks
#define ITEM_DAMP_ROCK 419
#define ITEM_HEAT_ROCK 420
#define ITEM_SMOOTH_ROCK 421
#define ITEM_ICY_ROCK 422

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB 423
#define ITEM_CELL_BATTERY 424
#define ITEM_LUMINOUS_MOSS 425
#define ITEM_SNOWBALL 426

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 427
#define ITEM_BRIGHTPOWDER ITEM_BRIGHT_POWDER // Pre-Gen VI name
#define ITEM_WHITE_HERB 428
#define ITEM_EXP_SHARE 429
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW 430
#define ITEM_SOOTHE_BELL 431
#define ITEM_MENTAL_HERB 432
#define ITEM_KINGS_ROCK 433
#define ITEM_AMULET_COIN 434
#define ITEM_CLEANSE_TAG 435
#define ITEM_SMOKE_BALL 436
#define ITEM_FOCUS_BAND 437
#define ITEM_LUCKY_EGG 438
#define ITEM_SCOPE_LENS 439
#define ITEM_LEFTOVERS 440
#define ITEM_SHELL_BELL 441
#define ITEM_WIDE_LENS 442
#define ITEM_MUSCLE_BAND 443
#define ITEM_WISE_GLASSES 444
#define ITEM_EXPERT_BELT 445
#define ITEM_LIGHT_CLAY 446
#define ITEM_LIFE_ORB 447
#define ITEM_POWER_HERB 448
#define ITEM_FOCUS_SASH 449
#define ITEM_ZOOM_LENS 450
#define ITEM_METRONOME 451
#define ITEM_IRON_BALL 452
#define ITEM_LAGGING_TAIL 453
#define ITEM_DESTINY_KNOT 454
#define ITEM_BLACK_SLUDGE 455
#define ITEM_GRIP_CLAW 456
#define ITEM_STICKY_BARB 457
#define ITEM_SHED_SHELL 458
#define ITEM_BIG_ROOT 459
#define ITEM_RAZOR_CLAW 460
#define ITEM_RAZOR_FANG 461
#define ITEM_EVIOLITE 462
#define ITEM_FLOAT_STONE 463
#define ITEM_ROCKY_HELMET 464
#define ITEM_AIR_BALLOON 465
#define ITEM_RED_CARD 466
#define ITEM_RING_TARGET 467
#define ITEM_BINDING_BAND 468
#define ITEM_EJECT_BUTTON 469
#define ITEM_WEAKNESS_POLICY 470
#define ITEM_ASSAULT_VEST 471
#define ITEM_SAFETY_GOGGLES 472
#define ITEM_ADRENALINE_ORB 473
#define ITEM_TERRAIN_EXTENDER 474
#define ITEM_PROTECTIVE_PADS 475
#define ITEM_THROAT_SPRAY 476
#define ITEM_EJECT_PACK 477
#define ITEM_HEAVY_DUTY_BOOTS 478
#define ITEM_BLUNDER_POLICY 479
#define ITEM_ROOM_SERVICE 480
#define ITEM_UTILITY_UMBRELLA 481

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
#define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
#define CONFUSE_BERRY_HEAL_FRACTION 2
#else
#define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define ITEM_CHERI_BERRY 482
#define ITEM_CHESTO_BERRY 483
#define ITEM_PECHA_BERRY 484
#define ITEM_RAWST_BERRY 485
#define ITEM_ASPEAR_BERRY 486
#define ITEM_LEPPA_BERRY 487
#define ITEM_ORAN_BERRY 488
#define ITEM_PERSIM_BERRY 489
#define ITEM_LUM_BERRY 490
#define ITEM_SITRUS_BERRY 491
#define ITEM_FIGY_BERRY 492
#define ITEM_WIKI_BERRY 493
#define ITEM_MAGO_BERRY 494
#define ITEM_AGUAV_BERRY 495
#define ITEM_IAPAPA_BERRY 496
#define ITEM_RAZZ_BERRY 497
#define ITEM_BLUK_BERRY 498
#define ITEM_NANAB_BERRY 499
#define ITEM_WEPEAR_BERRY 500
#define ITEM_PINAP_BERRY 501
#define ITEM_POMEG_BERRY 502
#define ITEM_KELPSY_BERRY 503
#define ITEM_QUALOT_BERRY 504
#define ITEM_HONDEW_BERRY 505
#define ITEM_GREPA_BERRY 506
#define ITEM_TAMATO_BERRY 507
#define ITEM_CORNN_BERRY 508
#define ITEM_MAGOST_BERRY 509
#define ITEM_RABUTA_BERRY 510
#define ITEM_NOMEL_BERRY 511
#define ITEM_SPELON_BERRY 512
#define ITEM_PAMTRE_BERRY 513
#define ITEM_WATMEL_BERRY 514
#define ITEM_DURIN_BERRY 515
#define ITEM_BELUE_BERRY 516
#define ITEM_CHILAN_BERRY 517
#define ITEM_OCCA_BERRY 518
#define ITEM_PASSHO_BERRY 519
#define ITEM_WACAN_BERRY 520
#define ITEM_RINDO_BERRY 521
#define ITEM_YACHE_BERRY 522
#define ITEM_CHOPLE_BERRY 523
#define ITEM_KEBIA_BERRY 524
#define ITEM_SHUCA_BERRY 525
#define ITEM_COBA_BERRY 526
#define ITEM_PAYAPA_BERRY 527
#define ITEM_TANGA_BERRY 528
#define ITEM_CHARTI_BERRY 529
#define ITEM_KASIB_BERRY 530
#define ITEM_HABAN_BERRY 531
#define ITEM_COLBUR_BERRY 532
#define ITEM_BABIRI_BERRY 533
#define ITEM_ROSELI_BERRY 534
#define ITEM_LIECHI_BERRY 535
#define ITEM_GANLON_BERRY 536
#define ITEM_SALAC_BERRY 537
#define ITEM_PETAYA_BERRY 538
#define ITEM_APICOT_BERRY 539
#define ITEM_LANSAT_BERRY 540
#define ITEM_STARF_BERRY 541
#define ITEM_ENIGMA_BERRY 542
#define ITEM_MICLE_BERRY 543
#define ITEM_CUSTAP_BERRY 544
#define ITEM_JABOCA_BERRY 545
#define ITEM_ROWAP_BERRY 546
#define ITEM_KEE_BERRY 547
#define ITEM_MARANGA_BERRY 548


// Apricorns
#define ITEM_RED_APRICORN 549
#define ITEM_BLUE_APRICORN 550
#define ITEM_BLU_APRICORN ITEM_BLUE_APRICORN // Pre-Gen VI name
#define ITEM_YELLOW_APRICORN 551
#define ITEM_YLW_APRICORN ITEM_YELLOW_APRICORN // Pre-Gen VI name
#define ITEM_GREEN_APRICORN 552
#define ITEM_GRN_APRICORN ITEM_GREEN_APRICORN // Pre-Gen VI name
#define ITEM_PINK_APRICORN 553
#define ITEM_PNK_APRICORN ITEM_PINK_APRICORN // Pre-Gen VI name
#define ITEM_WHITE_APRICORN 554
#define ITEM_WHT_APRICORN ITEM_WHITE_APRICORN // Pre-Gen VI name
#define ITEM_BLACK_APRICORN 555
#define ITEM_BLK_APRICORN ITEM_BLACK_APRICORN // Pre-Gen VI name
//new items
#define ITEM_BROWN_APRICORN 556
#define ITEM_BRN_APRICORN ITEM_BROWN_APRICORN //

//last berry
#define ITEM_ENIGMA_BERRY_E_READER 557

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX ITEM_ENIGMA_BERRY_E_READER

// futureproofing, adding the mints and the terrain seeds just below the berries,
// so if I want to add those to the farm I can just move the LAST_BERRY_INDEX stuff and not have to renumber a million things
// Mints
#define ITEM_LONELY_MINT 558
#define ITEM_ADAMANT_MINT 559
#define ITEM_NAUGHTY_MINT 560
#define ITEM_BRAVE_MINT 561
#define ITEM_BOLD_MINT 562
#define ITEM_IMPISH_MINT 563
#define ITEM_LAX_MINT 564
#define ITEM_RELAXED_MINT 565
#define ITEM_MODEST_MINT 566
#define ITEM_MILD_MINT 567
#define ITEM_RASH_MINT 568
#define ITEM_QUIET_MINT 569
#define ITEM_CALM_MINT 570
#define ITEM_GENTLE_MINT 571
#define ITEM_CAREFUL_MINT 572
#define ITEM_SASSY_MINT 573
#define ITEM_TIMID_MINT 574
#define ITEM_HASTY_MINT 575
#define ITEM_JOLLY_MINT 576
#define ITEM_NAIVE_MINT 577
#define ITEM_SERIOUS_MINT 578

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 579
#define ITEM_PSYCHIC_SEED 580
#define ITEM_MISTY_SEED 581
#define ITEM_GRASSY_SEED 582

// TMs/HMs
#define ITEM_TM01 583
#define ITEM_TM02 584
#define ITEM_TM03 585
#define ITEM_TM04 586
#define ITEM_TM05 587
#define ITEM_TM06 588
#define ITEM_TM07 589
#define ITEM_TM08 590
#define ITEM_TM09 591
#define ITEM_TM10 592
#define ITEM_TM11 593
#define ITEM_TM12 594
#define ITEM_TM13 595
#define ITEM_TM14 596
#define ITEM_TM15 597
#define ITEM_TM16 598
#define ITEM_TM17 599
#define ITEM_TM18 600
#define ITEM_TM19 601
#define ITEM_TM20 602
#define ITEM_TM21 603
#define ITEM_TM22 604
#define ITEM_TM23 605
#define ITEM_TM24 606
#define ITEM_TM25 607
#define ITEM_TM26 608
#define ITEM_TM27 609
#define ITEM_TM28 610
#define ITEM_TM29 611
#define ITEM_TM30 612
#define ITEM_TM31 613
#define ITEM_TM32 614
#define ITEM_TM33 615
#define ITEM_TM34 616
#define ITEM_TM35 617
#define ITEM_TM36 618
#define ITEM_TM37 619
#define ITEM_TM38 620
#define ITEM_TM39 621
#define ITEM_TM40 622
#define ITEM_TM41 623
#define ITEM_TM42 624
#define ITEM_TM43 625
#define ITEM_TM44 626
#define ITEM_TM45 627
#define ITEM_TM46 628
#define ITEM_TM47 629
#define ITEM_TM48 630
#define ITEM_TM49 631
#define ITEM_TM50 632
#define ITEM_TM51 633
#define ITEM_TM52 634
#define ITEM_TM53 635
#define ITEM_TM54 636
#define ITEM_TM55 637
#define ITEM_TM56 638
#define ITEM_TM57 639
#define ITEM_TM58 640
#define ITEM_TM59 641
#define ITEM_TM60 642
#define ITEM_TM61 643
#define ITEM_TM62 644
#define ITEM_TM63 645
#define ITEM_TM64 646
#define ITEM_TM65 647
#define ITEM_TM66 648
#define ITEM_TM67 649
#define ITEM_TM68 650
#define ITEM_TM69 651
#define ITEM_TM70 652
#define ITEM_TM71 653
#define ITEM_TM72 654
#define ITEM_TM73 655
#define ITEM_TM74 656
#define ITEM_TM75 657
#define ITEM_TM76 658
#define ITEM_TM77 659
#define ITEM_TM78 660
#define ITEM_TM79 661
#define ITEM_TM80 662
#define ITEM_TM81 663
#define ITEM_TM82 664
#define ITEM_TM83 665
#define ITEM_TM84 666
#define ITEM_TM85 667
#define ITEM_TM86 668
#define ITEM_TM87 669
#define ITEM_TM88 670
#define ITEM_TM89 671
#define ITEM_TM90 672
#define ITEM_TM91 673
#define ITEM_TM92 674
#define ITEM_TM93 675
#define ITEM_TM94 676
#define ITEM_TM95 677
#define ITEM_TM96 678
#define ITEM_TM97 679
#define ITEM_TM98 680
#define ITEM_TM99 681
#define ITEM_TM100 682

#define ITEM_HM01 683
#define ITEM_HM02 684
#define ITEM_HM03 685
#define ITEM_HM04 686
#define ITEM_HM05 687
#define ITEM_HM06 688
#define ITEM_HM07 689
#define ITEM_HM08 690

// Charms
#define ITEM_OVAL_CHARM 691
#define ITEM_SHINY_CHARM 692
#define ITEM_CATCHING_CHARM 693
#define ITEM_EXP_CHARM 694

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 695
#define ITEM_GRACIDEA 696
#define ITEM_REVEAL_GLASS 697
#define ITEM_DNA_SPLICERS 698
#define ITEM_ZYGARDE_CUBE 699
#define ITEM_PRISON_BOTTLE 700
#define ITEM_N_SOLARIZER 701
#define ITEM_N_LUNARIZER 702
#define ITEM_REINS_OF_UNITY 703

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 704
#define ITEM_Z_POWER_RING 705
#define ITEM_DYNAMAX_BAND 706

// Misc. Key Items
#define ITEM_BICYCLE 707
#define ITEM_MACH_BIKE 708
#define ITEM_ACRO_BIKE 709
#define ITEM_OLD_ROD 710
#define ITEM_GOOD_ROD 711
#define ITEM_SUPER_ROD 712
#define ITEM_DOWSING_MACHINE 713
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP 714
#define ITEM_VS_SEEKER 715
#define ITEM_TM_CASE 716
#define ITEM_BERRY_POUCH 717
#define ITEM_POKEMON_BOX_LINK 718
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 719
#define ITEM_POWDER_JAR 720
#define ITEM_WAILMER_PAIL 721
#define ITEM_POKE_RADAR 722
#define ITEM_POKEBLOCK_CASE 723
#define ITEM_SOOT_SACK 724
#define ITEM_POKE_FLUTE 725
#define ITEM_FAME_CHECKER 726
#define ITEM_TEACHY_TV 727

// Story Key Items
#define ITEM_SS_TICKET 728
#define ITEM_EON_TICKET 729
#define ITEM_MYSTIC_TICKET 730
#define ITEM_AURORA_TICKET 731
#define ITEM_OLD_SEA_MAP 732
#define ITEM_LETTER 733
#define ITEM_DEVON_PARTS 734
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 735
#define ITEM_DEVON_SCOPE 736
#define ITEM_BASEMENT_KEY 737
#define ITEM_SCANNER 738
#define ITEM_STORAGE_KEY 739
#define ITEM_KEY_TO_ROOM_1 740
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 741
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 742
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 743
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 744
#define ITEM_MAGMA_EMBLEM 745
#define ITEM_CONTEST_PASS 746
#define ITEM_PARCEL 747
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY 748
#define ITEM_BIKE_VOUCHER 749
#define ITEM_GOLD_TEETH 750
#define ITEM_CARD_KEY 751
#define ITEM_LIFT_KEY 752
#define ITEM_SILPH_SCOPE 753
#define ITEM_TRI_PASS 754
#define ITEM_RAINBOW_PASS 755
#define ITEM_TEA 756
#define ITEM_RUBY 757
#define ITEM_SAPPHIRE 758

// GEN IX ITEMS
#define ITEM_ABILITY_SHIELD 759
#define ITEM_CLEAR_AMULET 760
#define ITEM_PUNCHING_GLOVE 761
#define ITEM_COVERT_CLOAK 762
#define ITEM_LOADED_DICE 763
#define ITEM_AUSPICIOUS_ARMOR 764
#define ITEM_BOOSTER_ENERGY 765
#define ITEM_BIG_BAMBOO_SHOOT 766
#define ITEM_GIMMIGHOUL_COIN 767
#define ITEM_LEADERS_CREST 768
#define ITEM_MALICIOUS_ARMOR 769
#define ITEM_MIRROR_HERB 770
#define ITEM_SCROLL_OF_DARKNESS 771
#define ITEM_SCROLL_OF_WATERS 772
#define ITEM_TERA_ORB 773
#define ITEM_TINY_BAMBOO_SHOOT 774

#define ITEM_BUG_TERA_SHARD 775
#define ITEM_DARK_TERA_SHARD 776
#define ITEM_DRAGON_TERA_SHARD 777
#define ITEM_ELECTRIC_TERA_SHARD 778
#define ITEM_FAIRY_TERA_SHARD 779
#define ITEM_FIGHTING_TERA_SHARD 780
#define ITEM_FIRE_TERA_SHARD 781
#define ITEM_FLYING_TERA_SHARD 782
#define ITEM_GHOST_TERA_SHARD 783
#define ITEM_GRASS_TERA_SHARD 784
#define ITEM_GROUND_TERA_SHARD 785
#define ITEM_ICE_TERA_SHARD 786
#define ITEM_NORMAL_TERA_SHARD 787
#define ITEM_POISON_TERA_SHARD 788
#define ITEM_PSYCHIC_TERA_SHARD 789
#define ITEM_ROCK_TERA_SHARD 790
#define ITEM_STEEL_TERA_SHARD 791
#define ITEM_WATER_TERA_SHARD 792

#define ITEM_ADAMANT_CRYSTAL 793
#define ITEM_GRISEOUS_CORE 794
#define ITEM_LUSTROUS_GLOBE 795

#define ITEM_BLACK_AUGURITE 796
#define ITEM_LINKING_CORD 797
#define ITEM_PEAT_BLOCK 798
#define ITEM_BERSERK_GENE 799

#define ITEM_FAIRY_FEATHER 800
#define ITEM_SYRUPY_APPLE 801
#define ITEM_UNREMARKABLE_TEACUP 802
#define ITEM_MASTERPIECE_TEACUP 803
#define ITEM_CORNERSTONE_MASK 804
#define ITEM_WELLSPRING_MASK 805
#define ITEM_HEARTHFLAME_MASK 806
#define ITEM_HEALTH_MOCHI 807
#define ITEM_MUSCLE_MOCHI 808
#define ITEM_RESIST_MOCHI 809
#define ITEM_GENIUS_MOCHI 810
#define ITEM_CLEVER_MOCHI 811
#define ITEM_SWIFT_MOCHI 812
#define ITEM_FRESH_START_MOCHI 813
#define ITEM_GLIMMERING_CHARM 814
#define ITEM_METAL_ALLOY 815
#define ITEM_STELLAR_TERA_SHARD 816

#define ITEM_JUBILIFE_MUFFIN 817
#define ITEM_REMEDY 818
#define ITEM_FINE_REMEDY 819
#define ITEM_SUPERB_REMEDY 820
#define ITEM_AUX_EVASION 821
#define ITEM_AUX_GUARD 822
#define ITEM_AUX_POWER 823
#define ITEM_AUX_POWERGUARD 824
#define ITEM_CHOICE_DUMPLING 825
#define ITEM_SWAP_SNACK 826
#define ITEM_TWICE_SPICED_RADISH 827
#define ITEM_POKESHI_DOLL 828
=======
#define ITEM_CHERI_BERRY 514
#define ITEM_CHESTO_BERRY 515
#define ITEM_PECHA_BERRY 516
#define ITEM_RAWST_BERRY 517
#define ITEM_ASPEAR_BERRY 518
#define ITEM_LEPPA_BERRY 519
#define ITEM_ORAN_BERRY 520
#define ITEM_PERSIM_BERRY 521
#define ITEM_LUM_BERRY 522
#define ITEM_SITRUS_BERRY 523
#define ITEM_FIGY_BERRY 524
#define ITEM_WIKI_BERRY 525
#define ITEM_MAGO_BERRY 526
#define ITEM_AGUAV_BERRY 527
#define ITEM_IAPAPA_BERRY 528
#define ITEM_RAZZ_BERRY 529
#define ITEM_BLUK_BERRY 530
#define ITEM_NANAB_BERRY 531
#define ITEM_WEPEAR_BERRY 532
#define ITEM_PINAP_BERRY 533
#define ITEM_POMEG_BERRY 534
#define ITEM_KELPSY_BERRY 535
#define ITEM_QUALOT_BERRY 536
#define ITEM_HONDEW_BERRY 537
#define ITEM_GREPA_BERRY 538
#define ITEM_TAMATO_BERRY 539
#define ITEM_CORNN_BERRY 540
#define ITEM_MAGOST_BERRY 541
#define ITEM_RABUTA_BERRY 542
#define ITEM_NOMEL_BERRY 543
#define ITEM_SPELON_BERRY 544
#define ITEM_PAMTRE_BERRY 545
#define ITEM_WATMEL_BERRY 546
#define ITEM_DURIN_BERRY 547
#define ITEM_BELUE_BERRY 548
#define ITEM_CHILAN_BERRY 549
#define ITEM_OCCA_BERRY 550
#define ITEM_PASSHO_BERRY 551
#define ITEM_WACAN_BERRY 552
#define ITEM_RINDO_BERRY 553
#define ITEM_YACHE_BERRY 554
#define ITEM_CHOPLE_BERRY 555
#define ITEM_KEBIA_BERRY 556
#define ITEM_SHUCA_BERRY 557
#define ITEM_COBA_BERRY 558
#define ITEM_PAYAPA_BERRY 559
#define ITEM_TANGA_BERRY 560
#define ITEM_CHARTI_BERRY 561
#define ITEM_KASIB_BERRY 562
#define ITEM_HABAN_BERRY 563
#define ITEM_COLBUR_BERRY 564
#define ITEM_BABIRI_BERRY 565
#define ITEM_ROSELI_BERRY 566
#define ITEM_LIECHI_BERRY 567
#define ITEM_GANLON_BERRY 568
#define ITEM_SALAC_BERRY 569
#define ITEM_PETAYA_BERRY 570
#define ITEM_APICOT_BERRY 571
#define ITEM_LANSAT_BERRY 572
#define ITEM_STARF_BERRY 573
#define ITEM_ENIGMA_BERRY 574
#define ITEM_MICLE_BERRY 575
#define ITEM_CUSTAP_BERRY 576
#define ITEM_JABOCA_BERRY 577
#define ITEM_ROWAP_BERRY 578
#define ITEM_KEE_BERRY 579
#define ITEM_MARANGA_BERRY 580

//new berries
#define ITEM_HIPUP_BERRY 581
#define ITEM_PIPUP_BERRY 582
#define ITEM_PROTIE_BERRY 583
#define ITEM_EYEROH_BERRY 584
#define ITEM_CALCIE_BERRY 585
#define ITEM_ZINKIE_BERRY 586
#define ITEM_CARBO_BERRY 587

// last berry
#define ITEM_ENIGMA_BERRY_E_READER 588

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TM01 589
#define ITEM_TM02 590
#define ITEM_TM03 591
#define ITEM_TM04 592
#define ITEM_TM05 593
#define ITEM_TM06 594
#define ITEM_TM07 595
#define ITEM_TM08 596
#define ITEM_TM09 597
#define ITEM_TM10 598
#define ITEM_TM11 599
#define ITEM_TM12 600
#define ITEM_TM13 601
#define ITEM_TM14 602
#define ITEM_TM15 603
#define ITEM_TM16 604
#define ITEM_TM17 605
#define ITEM_TM18 606
#define ITEM_TM19 607
#define ITEM_TM20 608
#define ITEM_TM21 609
#define ITEM_TM22 610
#define ITEM_TM23 611
#define ITEM_TM24 612
#define ITEM_TM25 613
#define ITEM_TM26 614
#define ITEM_TM27 615
#define ITEM_TM28 616
#define ITEM_TM29 617
#define ITEM_TM30 618
#define ITEM_TM31 619
#define ITEM_TM32 620
#define ITEM_TM33 621
#define ITEM_TM34 622
#define ITEM_TM35 623
#define ITEM_TM36 624
#define ITEM_TM37 625
#define ITEM_TM38 626
#define ITEM_TM39 627
#define ITEM_TM40 628
#define ITEM_TM41 629
#define ITEM_TM42 630
#define ITEM_TM43 631
#define ITEM_TM44 632
#define ITEM_TM45 633
#define ITEM_TM46 634
#define ITEM_TM47 635
#define ITEM_TM48 636
#define ITEM_TM49 637
#define ITEM_TM50 638
#define ITEM_TM51 639
#define ITEM_TM52 640
#define ITEM_TM53 641
#define ITEM_TM54 642
#define ITEM_TM55 643
#define ITEM_TM56 644
#define ITEM_TM57 645
#define ITEM_TM58 646
#define ITEM_TM59 647
#define ITEM_TM60 648
#define ITEM_TM61 649
#define ITEM_TM62 650
#define ITEM_TM63 651
#define ITEM_TM64 652
#define ITEM_TM65 653
#define ITEM_TM66 654
#define ITEM_TM67 655
#define ITEM_TM68 656
#define ITEM_TM69 657
#define ITEM_TM70 658
#define ITEM_TM71 659
#define ITEM_TM72 660
#define ITEM_TM73 661
#define ITEM_TM74 662
#define ITEM_TM75 663
#define ITEM_TM76 664
#define ITEM_TM77 665
#define ITEM_TM78 666
#define ITEM_TM79 667
#define ITEM_TM80 668
#define ITEM_TM81 669
#define ITEM_TM82 670
#define ITEM_TM83 671
#define ITEM_TM84 672
#define ITEM_TM85 673
#define ITEM_TM86 674
#define ITEM_TM87 675
#define ITEM_TM88 676
#define ITEM_TM89 677
#define ITEM_TM90 678
#define ITEM_TM91 679
#define ITEM_TM92 680
#define ITEM_TM93 681
#define ITEM_TM94 682
#define ITEM_TM95 683
#define ITEM_TM96 684
#define ITEM_TM97 685
#define ITEM_TM98 686
#define ITEM_TM99 687
#define ITEM_TM100 688

#define ITEM_HM01 689
#define ITEM_HM02 690
#define ITEM_HM03 691
#define ITEM_HM04 692
#define ITEM_HM05 693
#define ITEM_HM06 694
#define ITEM_HM07 695
#define ITEM_HM08 696

// Charms
#define ITEM_OVAL_CHARM 697
#define ITEM_SHINY_CHARM 698
#define ITEM_CATCHING_CHARM 699
#define ITEM_EXP_CHARM 700

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 701
#define ITEM_GRACIDEA 702
#define ITEM_REVEAL_GLASS 703
#define ITEM_DNA_SPLICERS 704
#define ITEM_ZYGARDE_CUBE 705
#define ITEM_PRISON_BOTTLE 706
#define ITEM_N_SOLARIZER 707
#define ITEM_N_LUNARIZER 708
#define ITEM_REINS_OF_UNITY 709

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 710
#define ITEM_Z_POWER_RING 711
#define ITEM_DYNAMAX_BAND 712

// Misc. Key Items
#define ITEM_BICYCLE 713
#define ITEM_MACH_BIKE 714
#define ITEM_ACRO_BIKE 715
#define ITEM_OLD_ROD 716
#define ITEM_GOOD_ROD 717
#define ITEM_SUPER_ROD 718
#define ITEM_DOWSING_MACHINE 719
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP 720
#define ITEM_VS_SEEKER 721
#define ITEM_TM_CASE 722
#define ITEM_BERRY_POUCH 723
#define ITEM_POKEMON_BOX_LINK 724
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 725
#define ITEM_POWDER_JAR 726
#define ITEM_WAILMER_PAIL 727
#define ITEM_POKE_RADAR 728
#define ITEM_POKEBLOCK_CASE 729
#define ITEM_SOOT_SACK 730
#define ITEM_POKE_FLUTE 731
#define ITEM_FAME_CHECKER 732
#define ITEM_TEACHY_TV 733

// Story Key Items
#define ITEM_SS_TICKET 734
#define ITEM_EON_TICKET 735
#define ITEM_MYSTIC_TICKET 736
#define ITEM_AURORA_TICKET 737
#define ITEM_OLD_SEA_MAP 738
#define ITEM_LETTER 739
#define ITEM_DEVON_PARTS 740
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 741
#define ITEM_DEVON_SCOPE 742
#define ITEM_BASEMENT_KEY 743
#define ITEM_SCANNER 744
#define ITEM_STORAGE_KEY 745
#define ITEM_KEY_TO_ROOM_1 746
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 747
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 748
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 749
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 750
#define ITEM_MAGMA_EMBLEM 751
#define ITEM_CONTEST_PASS 752
#define ITEM_PARCEL 753
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY 754
#define ITEM_BIKE_VOUCHER 755
#define ITEM_GOLD_TEETH 756
#define ITEM_CARD_KEY 757
#define ITEM_LIFT_KEY 758
#define ITEM_SILPH_SCOPE 759
#define ITEM_TRI_PASS 760
#define ITEM_RAINBOW_PASS 761
#define ITEM_TEA 762
#define ITEM_RUBY 763
#define ITEM_SAPPHIRE 764

// GEN IX ITEMS
#define ITEM_ABILITY_SHIELD 765
#define ITEM_CLEAR_AMULET 766
#define ITEM_PUNCHING_GLOVE 767
#define ITEM_COVERT_CLOAK 768
#define ITEM_LOADED_DICE 769
#define ITEM_AUSPICIOUS_ARMOR 770
#define ITEM_BOOSTER_ENERGY 771
#define ITEM_BIG_BAMBOO_SHOOT 772
#define ITEM_GIMMIGHOUL_COIN 773
#define ITEM_LEADERS_CREST 774
#define ITEM_MALICIOUS_ARMOR 775
#define ITEM_MIRROR_HERB 776
#define ITEM_SCROLL_OF_DARKNESS 777
#define ITEM_SCROLL_OF_WATERS 778
#define ITEM_TERA_ORB 779
#define ITEM_TINY_BAMBOO_SHOOT 780

#define ITEM_BUG_TERA_SHARD 781
#define ITEM_DARK_TERA_SHARD 782
#define ITEM_DRAGON_TERA_SHARD 783
#define ITEM_ELECTRIC_TERA_SHARD 784
#define ITEM_FAIRY_TERA_SHARD 785
#define ITEM_FIGHTING_TERA_SHARD 786
#define ITEM_FIRE_TERA_SHARD 787
#define ITEM_FLYING_TERA_SHARD 788
#define ITEM_GHOST_TERA_SHARD 789
#define ITEM_GRASS_TERA_SHARD 790
#define ITEM_GROUND_TERA_SHARD 791
#define ITEM_ICE_TERA_SHARD 792
#define ITEM_NORMAL_TERA_SHARD 793
#define ITEM_POISON_TERA_SHARD 794
#define ITEM_PSYCHIC_TERA_SHARD 795
#define ITEM_ROCK_TERA_SHARD 796
#define ITEM_STEEL_TERA_SHARD 797
#define ITEM_WATER_TERA_SHARD 798

#define ITEM_ADAMANT_CRYSTAL 799
#define ITEM_GRISEOUS_CORE 800
#define ITEM_LUSTROUS_GLOBE 801

#define ITEM_BLACK_AUGURITE 802
#define ITEM_LINKING_CORD 803
#define ITEM_PEAT_BLOCK 804
#define ITEM_BERSERK_GENE 805

#define ITEM_FAIRY_FEATHER 806
#define ITEM_SYRUPY_APPLE 807
#define ITEM_UNREMARKABLE_TEACUP 808
#define ITEM_MASTERPIECE_TEACUP 809
#define ITEM_CORNERSTONE_MASK 810
#define ITEM_WELLSPRING_MASK 811
#define ITEM_HEARTHFLAME_MASK 812
#define ITEM_HEALTH_MOCHI 813
#define ITEM_MUSCLE_MOCHI 814
#define ITEM_RESIST_MOCHI 815
#define ITEM_GENIUS_MOCHI 816
#define ITEM_CLEVER_MOCHI 817
#define ITEM_SWIFT_MOCHI 818
#define ITEM_FRESH_START_MOCHI 819
#define ITEM_GLIMMERING_CHARM 820
#define ITEM_METAL_ALLOY 821
#define ITEM_STELLAR_TERA_SHARD 822

#define ITEM_JUBILIFE_MUFFIN 823
#define ITEM_REMEDY 824
#define ITEM_FINE_REMEDY 825
#define ITEM_SUPERB_REMEDY 826
#define ITEM_AUX_EVASION 827
#define ITEM_AUX_GUARD 828
#define ITEM_AUX_POWER 829
#define ITEM_AUX_POWERGUARD 830
#define ITEM_CHOICE_DUMPLING 831
#define ITEM_SWAP_SNACK 832
#define ITEM_TWICE_SPICED_RADISH 833
#define ITEM_POKESHI_DOLL 834

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT 835

#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 100
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
